- hosts: localhost
  gather_facts: false

  tasks:
  - wait_for:
      port: 22
      host: '{{ groups["testhost"][0] }}'
      timeout: 1200

- hosts: testhost
  gather_facts: false

  tasks:
  - name: Wait for EC2 to be available
    wait_for_connection:

  - amazon.aws.ec2_metadata_facts:
